### PR TITLE
feat: adding environment awareness

### PR DESCRIPTION
**Pull request by thlorenz**
## Summary

Adding environment awareness to Geyser plugin.

## Details

Instead of one URL to get list to of supported programs and one kafka cluster to send updates for them
to we now support multiple, each representing a different environment.

Thus the config will now have to provide a combinatation of  `(listUrl, kafkaConfig)` in the
`environments` collection.

* * *

Quoting the updated config description from the readme:
## Config

The config is specified via the plugin's JSON config file. It contains settings that apply to all
environments and some that are environment specific.

### Environment Config Values

This config needs to be added per environment. Thus using different allow list settings for
different Kafka clusters is possible. Each item in the `environments` array is an `EnvConfig`
and follows the below schema.

* **name** (`String`)
    * Name of the environment
* **kafka** (`HashMap<String, String>`)
    * Kafka [`librdkafka` config options](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md).
* **program_allowlist** (`Vec<String>`)
    * Allowlist of programs to publish.
        * If empty, all accounts are published.
        * If not empty, only accounts owned by programs in this list are published.
* **program_allowlist_url** (`String`)
    * URL to fetch allowlist updates from
    * The file must be json, and with the following schema:
      ```json
      {
        "result": [
            "11111111111111111111111111111111",
            "22222222222222222222222222222222"
        ]
      }
      ```
* **program_allowlist_auth** (`String`)
    * Allowlist Authorization header value.
        * If provided the request to the program_allowlist_url will add an
            'Authorization: <value>' header.
        * A sample auth header value would be 'Bearer my_long_secret_token'.
* **program_allowlist_expiry_sec** (`u64`)
    * Update iterval for allowlist from http url.

### Global Config Values

The below config values are global and apply to all environments. Environment specific settings
are added to the `environments` array.

* **shutdown_timeout_ms** (`u64`)
    * Time the plugin is given to flush out all messages to Kafka
        * and gracefully shutdown upon exit request.
* **update_account_topic** (`String`)
    * Kafka topic to send account updates to.
        * Omit to disable.
* **slot_status_topic** (`String`)
    * Kafka topic to send slot status updates to.
        * Omit to disable.
* **transaction_topic** (`String`)
    * Kafka topic to send transaction updates to.
        * Omit to disable.
* **publish_all_accounts** (`bool`)
    * Publish all accounts on startup.
        * Omit to disable.
* **publish_accounts_without_signature** (`bool`)
    * Publishes account updates even if the txn_signature is not present.
        * This will include account updates that occur without a corresponding
            * transaction, i.e. caused by validator book-keeping.
        * Omit to disable.
* **wrap_messages** (`bool`)
    * Wrap all messages in a unified wrapper object.
        * Omit to disable.
* **environments** (`Vec<EnvConfig>`)
    * Kafka cluster and allow list configs for different environments.
        * See [EnvConfig].

### Example Config

```json
{
  "libpath": "/home/solana/geyser-kafka/target/release/libsolana_accountsdb_plugin_kafka.so",
  "shutdown_timeout_ms": 30000,
  "update_account_topic": "geyser.mainnet.account_update",
  "update_slot_topic": "geyser.mainnet.slot_update",
  "update_transaction_topic": "geyser.mainnet.transaction_update",
  "publish_all_accounts": false,
  "publish_accounts_without_signature": false,
  "wrap_messages": false,
  "environments": [
    {
      "name": "dev",
      "program_allowlist_url": "https://example.com/supported-programs",
      "program_allowlist_auth": "Bearer <dev secret bearer token>",
      "program_allowlist_expiry_sec": 30,
      "kafka": {
        "bootstrap.servers": "dev.bootstrap-server:9092",
        "sasl.username": "<username>",
        "sasl.password": "<base64 encoded password>",
        "sasl.mechanism": "SCRAM-SHA-256",
        "security.protocol": "SASL_SSL",
        "request.required.acks": "1",
        "message.timeout.ms": "30000",
        "compression.type": "lz4",
        "partitioner": "random"
      }
    },
    {
      "name": "stage",
      "program_allowlist_url": "https://example.com/supported-programs",
      "program_allowlist_auth": "Bearer <stage secret bearer token>",
      "program_allowlist_expiry_sec": 15,
      "kafka": {
        "bootstrap.servers": "stage.bootstrap-server:9092",
        "sasl.username": "<username>",
        "sasl.password": "<base64 encoded password>",
        "sasl.mechanism": "SCRAM-SHA-256",
        "security.protocol": "SASL_SSL",
        "request.required.acks": "1",
        "message.timeout.ms": "30000",
        "compression.type": "lz4",
        "partitioner": "random"
      }
    }
  ]
}
```

We assume that the same topics are configured in each kafka cluster.

### CODE REVIEW

**Comment by italoacasas** [comment]
Not working. Unfortunately, the logs are not showing too much information.

`[2023-06-19T12:45:37.320484647Z ERROR librdkafka] librdkafka: FAIL [thrd:sasl_ssl://diverse-alpaca-10076-us1-kafka.upstash.io:9092/boots]: sasl_ssl://diverse-alpaca-10076-us1-kafka.upstash.io:9092/bootstrap: SASL authentication error: SaslAuthenticateRequest failed: Local: Broker handle destroyed (after 0ms in state DOWN)`

**Comment by thlorenz** [comment]
I'll have a look. Might be due to multiple threaded publishers not working since the plugin was not set up for this scenario.

This will be tricky to triage.

I'll look into simplifying the publisher setup.

**Comment by thlorenz** [comment]
> [2023-06-19T12:45:37.320484647Z ERROR librdkafka] librdkafka: 
>   FAIL [thrd:sasl_ssl://diverse-alpaca-10076-us1-kafka.upstash.io:9092/boots]: 
>     sasl_ssl://diverse-alpaca-10076-us1-kafka.upstash.io:9092/bootstrap: 
>       SASL authentication error: 
>          SaslAuthenticateRequest failed: 
>             Local: Broker handle destroyed (after 0ms in state DOWN)

For reference this is what Chat GPT recommends:

The error message suggests that there is an issue with the SASL authentication while connecting to the Kafka broker hosted by Upstash. Here are a few troubleshooting steps you can follow:

1. Verify the SASL authentication credentials: Make sure you have provided the correct SASL authentication credentials, such as username and password, in your Rust program. Double-check the accuracy of these credentials, as any mismatch can result in authentication failures.

2. Check the Kafka broker configuration: Ensure that the Kafka broker configuration on the Upstash platform is correctly set up to support SASL authentication. The broker should be configured to accept SASL connections and authenticate them using the provided credentials.

3. Verify network connectivity: Ensure that your Rust program can establish a network connection with the Kafka broker. Check for any network-related issues, such as firewall rules or network restrictions, that might be preventing the connection.

4. Check for any library or version compatibility issues: Make sure you are using compatible versions of the libraries required for Kafka integration in your Rust program. Check the documentation or release notes of the libraries to ensure they are compatible with each other and with the version of Kafka you are using.

5. Review the logs: Examine the logs from the Kafka broker or any additional logging mechanisms in your Rust program to gather more information about the failure. Logs may provide additional details about the cause of the authentication error.

If the issue persists after going through these steps, it might be helpful to reach out to Upstash support or consult their documentation for specific guidance on connecting to their Kafka service using SASL authentication from a Rust program.

**Comment by thlorenz** [comment]
Issue was fixed after the config was updated to the above described schema.

**Review by italoacasas — APPROVED** [review]

**Pull request merged**
